import AppKit

/// macOS 没有剪贴板变更通知 API，只能轮询 `NSPasteboard.changeCount`。
final class ClipboardMonitor {
    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount

    /// 我们自己写剪贴板时产生的 changeCount。轮询时跳过它们，
    /// 否则「粘贴 → 恢复原剪贴板」这两次写入会被当成用户复制，把历史搞乱。
    ///
    /// 用精确的 changeCount 而不是「一段时间内全部忽略」：时间窗口会误吞
    /// 用户在这个窗口里真正复制的内容。
    private var selfWrites: Set<Int> = []

    var onNewItem: ((ClipItem) -> Void)?

    /// 记录一次「这是我们自己写的」。写完之后立刻调用。
    func noteSelfWrite(_ changeCount: Int) {
        selfWrites.insert(changeCount)
    }

    /// nspasteboard.org 约定：密码管理器/临时内容会打上这些标记，必须跳过。
    private let concealedTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
    ]

    func start(interval: TimeInterval = 0.3) {
        guard timer == nil else { return }
        let t = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            self?.poll()
        }
        // .common 模式：菜单弹出、拖拽时轮询也不会停
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// 立刻同步轮询一次，不等定时器。
    ///
    /// 定时器是 0.3 秒一轮，而用户「复制 → 马上按 Ctrl+V」的间隔常常比这短。
    /// 所以两个关键时机必须主动刷一次：
    ///
    /// - 呼出面板之前 —— 否则面板显示的是一份不含刚复制内容的旧列表
    /// - 覆盖剪贴板之前 —— 否则那次复制会被我们自己的写入盖掉，永久丢失
    func pollNow() {
        poll()
    }

    private func poll() {
        let pb = NSPasteboard.general

        // 先比 changeCount 再读内容：大图/大文本才不会每 0.3 秒被复制一遍
        guard pb.changeCount != lastChangeCount else { return }
        let changeCount = pb.changeCount
        lastChangeCount = changeCount

        // 是我们自己造成的写入 → 跳过，但 changeCount 已经记下了
        if selfWrites.remove(changeCount) != nil {
            Log.info("跳过自身写入（changeCount \(changeCount)）")
            return
        }
        // 顺手清掉更早的陈旧记录，changeCount 只增不减
        selfWrites = selfWrites.filter { $0 > changeCount }

        let types = Set(pb.types ?? [])
        guard types.isDisjoint(with: concealedTypes) else {
            Log.info("跳过受保护内容（密码管理器 / 临时剪贴板）")
            return
        }

        guard let item = ClipItem.capture(
            from: pb,
            sourceApp: NSWorkspace.shared.frontmostApplication?.localizedName
        ) else {
            Log.info("跳过：没有可保存的类型，或体积超过 \(ClipItem.maxItemBytes / 1024 / 1024) MB")
            return
        }

        onNewItem?(item)
    }
}
